ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BILLING_CHECKOUT_STARTED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BILLING_PORTAL_OPENED';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'BILLING_PLAN_UPDATED';
