-- AlterEnum
ALTER TYPE "SourceType" ADD VALUE IF NOT EXISTS 'REDDIT_SEARCH';

-- AlterEnum
ALTER TYPE "SourceType" ADD VALUE IF NOT EXISTS 'HN_SEARCH';

-- AlterEnum
ALTER TYPE "SourceType" ADD VALUE IF NOT EXISTS 'WEB_SEARCH';
